---
# Advanced HPA with custom metrics
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sre-demo-hpa-advanced
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-demo-app
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 5
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60

---
# Performance testing namespace
apiVersion: v1
kind: Namespace
metadata:
  name: performance-testing
  labels:
    purpose: performance-testing

---
# Resource quotas for performance testing
apiVersion: v1
kind: ResourceQuota
metadata:
  name: performance-test-quota
  namespace: performance-testing
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"

---
# Performance optimization ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-config
  namespace: default
data:
  optimization.yaml: |
    performance_targets:
      p50_latency: 100ms
      p95_latency: 300ms
      p99_latency: 500ms
      throughput: 1000rps
      error_rate: <1%
      availability: 99.9%
    
    optimization_strategies:
      - name: connection_pooling
        enabled: true
        config:
          max_connections: 100
          connection_timeout: 30s
      - name: caching
        enabled: true
        config:
          cache_ttl: 300s
          max_cache_size: 100MB
      - name: compression
        enabled: true
        config:
          gzip_level: 6
    
    capacity_planning:
      growth_rate: 20%
      peak_multiplier: 3
      safety_margin: 25%

---
# Pod Disruption Budget for availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sre-demo-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sre-demo-app

---
# Network Policy for performance testing isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: performance-test-isolation
  namespace: performance-testing
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: performance-testing
    - namespaceSelector:
        matchLabels:
          name: default
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: default
  - to: []
    ports:
    - protocol: UDP
      port: 53