apiVersion: v1
kind: ConfigMap
metadata:
  name: rollback-policies
  namespace: default
  labels:
    app: sre-demo-app
    component: rollback-automation
data:
  # Automated rollback rules and policies
  rollback-rules.yaml: |
    # Rollback Rules Configuration
    # Defines when and how automated rollbacks should be triggered
    
    rollback_policy:
      name: "SRE Demo App Rollback Policy"
      version: "1.0"
      last_updated: "2024-01-15"
      
      # Global rollback settings
      global_settings:
        rollback_method: "argocd"          # argocd or kubectl
        max_rollback_attempts: 3           # Maximum automatic rollback attempts
        rollback_cooldown: "600s"          # Wait time between rollback attempts
        validation_window: "300s"          # Time to validate rollback success
        
      # Trigger conditions for automatic rollback
      trigger_conditions:
        immediate_triggers:
          - name: "Service Unavailable"
            condition: "up{job=\"sre-demo-app\"} == 0"
            duration: "120s"
            severity: "critical"
            action: "immediate_rollback"
            description: "Service completely unavailable - immediate rollback required"
            
          - name: "Extreme Error Rate"
            condition: |
              (
                sum(rate(http_requests_total{status_code=~"5.."}[5m])) /
                sum(rate(http_requests_total[5m]))
              ) * 100 > 15
            duration: "180s"
            severity: "critical"
            action: "immediate_rollback"
            description: "Error rate above 15% indicates severe deployment issues"
            
          - name: "Critical Latency"
            condition: |
              histogram_quantile(0.95, 
                sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
              ) > 3.0
            duration: "300s"
            severity: "critical"
            action: "immediate_rollback"
            description: "P95 latency above 3 seconds indicates severe performance degradation"
        
        warning_triggers:
          - name: "Elevated Error Rate"
            condition: |
              (
                sum(rate(http_requests_total{status_code=~"5.."}[5m])) /
                sum(rate(http_requests_total[5m]))
              ) * 100 > 8
            duration: "600s"
            severity: "warning"
            action: "conditional_rollback"
            description: "Sustained error rate above 8% may require rollback"
            
          - name: "High Latency"
            condition: |
              histogram_quantile(0.95, 
                sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
              ) > 1.5
            duration: "900s"
            severity: "warning"
            action: "conditional_rollback"
            description: "Sustained high latency may impact user experience"
            
          - name: "Business Operation Degradation"
            condition: |
              (
                sum(rate(business_operations_total{status="success"}[5m])) /
                sum(rate(business_operations_total[5m]))
              ) * 100 < 90
            duration: "600s"
            severity: "warning"
            action: "conditional_rollback"
            description: "Business operation success rate below 90%"
      
      # Rollback execution strategy
      execution_strategy:
        immediate_rollback:
          method: "argocd_history_rollback"
          validation_required: true
          notification_channels:
            - "slack://sre-critical"
            - "email://sre-oncall"
            - "pagerduty://sre-team"
          
        conditional_rollback:
          method: "argocd_history_rollback"
          validation_required: true
          approval_required: false
          notification_channels:
            - "slack://sre-alerts"
            - "email://sre-team"
        
        manual_rollback:
          method: "kubectl_rollout_undo"
          validation_required: true
          approval_required: true
          notification_channels:
            - "slack://sre-alerts"
      
      # Post-rollback validation
      validation_criteria:
        availability_threshold: 99.0
        latency_threshold: 0.5
        error_rate_threshold: 2.0
        business_success_threshold: 95.0
        validation_duration: "300s"
        stability_period: "600s"

  # Rollback notification templates
  notification-templates.yaml: |
    # Notification Templates for Rollback Events
    
    rollback_triggered:
      slack_template: |
        🔄 *Automated Rollback Triggered*
        
        *Service*: {{ .service }}
        *Trigger*: {{ .trigger_condition }}
        *Severity*: {{ .severity }}
        *Rollback Method*: {{ .rollback_method }}
        
        *Current Metrics*:
        • Availability: {{ .current_availability }}%
        • Error Rate: {{ .current_error_rate }}%
        • P95 Latency: {{ .current_latency }}s
        
        *Action*: Rollback to revision {{ .target_revision }}
        *ETA*: {{ .estimated_completion }}
        
        Monitor progress: {{ .argocd_url }}
        
      email_template: |
        Subject: 🔄 Automated Rollback Triggered - {{ .service }}
        
        An automated rollback has been triggered for {{ .service }} due to SLO violations.
        
        Trigger Condition: {{ .trigger_condition }}
        Severity: {{ .severity }}
        Rollback Method: {{ .rollback_method }}
        Target Revision: {{ .target_revision }}
        
        Current SLO Metrics:
        - Availability: {{ .current_availability }}%
        - Error Rate: {{ .current_error_rate }}%
        - P95 Latency: {{ .current_latency }}s
        
        Rollback initiated at: {{ .timestamp }}
        Expected completion: {{ .estimated_completion }}
        
        Monitor at: {{ .argocd_url }}
        Runbook: {{ .runbook_url }}
    
    rollback_completed:
      slack_template: |
        ✅ *Rollback Completed Successfully*
        
        *Service*: {{ .service }}
        *Rollback Duration*: {{ .rollback_duration }}
        *New Revision*: {{ .new_revision }}
        
        *Post-Rollback Metrics*:
        • Availability: {{ .post_availability }}%
        • Error Rate: {{ .post_error_rate }}%
        • P95 Latency: {{ .post_latency }}s
        
        *Status*: Service stability restored
        
      email_template: |
        Subject: ✅ Rollback Completed - {{ .service }}
        
        The automated rollback for {{ .service }} has completed successfully.
        
        Rollback Summary:
        - Duration: {{ .rollback_duration }}
        - Target Revision: {{ .target_revision }}
        - Current Revision: {{ .new_revision }}
        
        Post-Rollback SLO Metrics:
        - Availability: {{ .post_availability }}%
        - Error Rate: {{ .post_error_rate }}%
        - P95 Latency: {{ .post_latency }}s
        
        Service stability has been restored. Normal operations can resume.
        
        Next Steps:
        - Investigate root cause of deployment issue
        - Update deployment process if needed
        - Schedule post-incident review
    
    rollback_failed:
      slack_template: |
        🚨 *Rollback Failed - Manual Intervention Required*
        
        *Service*: {{ .service }}
        *Rollback Attempt*: {{ .attempt_number }}/{{ .max_attempts }}
        *Failure Reason*: {{ .failure_reason }}
        
        *Current Status*:
        • Availability: {{ .current_availability }}%
        • Error Rate: {{ .current_error_rate }}%
        • P95 Latency: {{ .current_latency }}s
        
        🚨 *URGENT*: Manual intervention required immediately
        
        Escalation: {{ .escalation_contact }}
        Runbook: {{ .runbook_url }}
        
      email_template: |
        Subject: 🚨 URGENT: Rollback Failed - {{ .service }}
        
        URGENT: The automated rollback for {{ .service }} has failed and manual intervention is required immediately.
        
        Failure Details:
        - Rollback Attempt: {{ .attempt_number }}/{{ .max_attempts }}
        - Failure Reason: {{ .failure_reason }}
        - Failed at: {{ .timestamp }}
        
        Current SLO Status:
        - Availability: {{ .current_availability }}%
        - Error Rate: {{ .current_error_rate }}%
        - P95 Latency: {{ .current_latency }}s
        
        REQUIRED ACTIONS:
        1. Acknowledge this incident immediately
        2. Follow emergency runbook: {{ .runbook_url }}
        3. Escalate to: {{ .escalation_contact }}
        4. Consider manual rollback or service isolation
        
        This is a critical incident requiring immediate response.

  # Rollback decision matrix
  decision-matrix.yaml: |
    # Rollback Decision Matrix
    # Decision tree for rollback actions based on multiple conditions
    
    decision_rules:
      # Multiple violations = immediate rollback
      high_risk_scenarios:
        - conditions: ["service_unavailable", "high_error_rate"]
          action: "immediate_rollback"
          priority: "critical"
          
        - conditions: ["extreme_latency", "high_error_rate"]
          action: "immediate_rollback"
          priority: "critical"
          
        - conditions: ["resource_exhaustion", "elevated_error_rate"]
          action: "immediate_rollback"
          priority: "high"
      
      # Single violations = conditional rollback
      moderate_risk_scenarios:
        - conditions: ["elevated_error_rate"]
          action: "conditional_rollback"
          priority: "medium"
          wait_time: "300s"
          
        - conditions: ["high_latency"]
          action: "conditional_rollback"
          priority: "medium"
          wait_time: "600s"
          
        - conditions: ["business_operation_degradation"]
          action: "investigation_required"
          priority: "medium"
          wait_time: "900s"
      
      # Low risk = monitoring
      low_risk_scenarios:
        - conditions: ["minor_latency_increase"]
          action: "enhanced_monitoring"
          priority: "low"
          
        - conditions: ["resource_usage_trending_up"]
          action: "capacity_review"
          priority: "low"
    
    # Rollback success validation
    success_validation:
      required_metrics:
        availability: "> 99.0%"
        error_rate: "< 2.0%"
        latency_p95: "< 0.6s"
        business_success: "> 97.0%"
      
      validation_duration: "300s"
      stability_check_duration: "600s"
      
    # Escalation paths
    escalation_paths:
      rollback_success:
        - "log_incident_resolution"
        - "notify_stakeholders"
        - "schedule_postmortem"
        
      rollback_failure:
        - "escalate_to_senior_sre"
        - "activate_incident_bridge"
        - "consider_service_isolation"
        
      repeated_failures:
        - "escalate_to_engineering_manager"
        - "review_deployment_process"
        - "implement_additional_safeguards"