apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-demo-app
  labels:
    app: sre-demo-app
    version: v1.2.0
    component: backend
    deployment.method: gitops
  annotations:
    deployment.kubernetes.io/revision: "1"
    gitops.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: sre-demo-app
  template:
    metadata:
      labels:
        app: sre-demo-app
        version: v1.2.0
        component: backend
        deployment.method: gitops
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        deployment.timestamp: "2024-01-01T00:00:00Z"
    spec:
      containers:
      - name: sre-demo-app
        image: us-central1-docker.pkg.dev/gcp-sre-lab/sre-demo-app/sre-demo-app:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: "production"
        - name: LOG_FORMAT
          value: "json"
        - name: LOG_LEVEL
          value: "INFO"
        - name: APP_VERSION
          value: "1.2.0"
        - name: DEPLOYMENT_METHOD
          value: "gitops"
        - name: GIT_COMMIT
          value: "unknown"
        - name: DEPLOYMENT_ID
          value: "gitops"
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: sre-demo-config
              key: app.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
