apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: default
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'console-receiver'
      routes:
      - match:
          severity: critical
        receiver: 'critical-console'
        group_wait: 0s
        group_interval: 5m
        repeat_interval: 15m
      - match:
          severity: warning
        receiver: 'warning-console'
        group_wait: 5m
        group_interval: 10m
        repeat_interval: 4h

    inhibit_rules:
    - source_match:
        alertname: ServiceUnavailable
      target_match:
        service: sre-demo-app
      equal: ['service']

    receivers:
    - name: 'console-receiver'
    - name: 'critical-console'
    - name: 'warning-console'

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: default
type: Opaque
stringData:
  placeholder: "educational-environment"