apiVersion: v1
kind: ConfigMap
metadata:
  name: gmp-config
  namespace: default
data:
  config.yaml: |
    global:
      external_labels:
        cluster: sre-demo-cluster
        location: us-central1
    scrape_configs:
    - job_name: 'sre-demo-app-gmp'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_requests_total|business_operations_total|application_info'
        action: keep

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sre-demo-app-monitor
  labels:
    app: sre-demo-app
spec:
  selector:
    matchLabels:
      app: sre-demo-app
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 30s