apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-validation-queries
  namespace: default
  labels:
    app: sre-demo-app
    component: monitoring
data:
  # Availability SLO Query - Percentage of successful HTTP requests
  availability_slo.promql: |
    sum(rate(http_requests_total{status_code!~"5.."}[5m])) / 
    sum(rate(http_requests_total[5m])) * 100

  # Latency SLO Query - P95 latency under 500ms
  latency_slo.promql: |
    histogram_quantile(0.95, 
      sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
    ) < 0.5

  # Error Rate Query - Percentage of 5xx errors
  error_rate.promql: |
    sum(rate(http_requests_total{status_code=~"5.."}[5m])) / 
    sum(rate(http_requests_total[5m])) * 100

  # Business Operations Success Rate
  business_operations_slo.promql: |
    sum(rate(business_operations_total{status="success"}[5m])) / 
    sum(rate(business_operations_total[5m])) * 100

  # Service Up Status
  service_up.promql: |
    up{job="sre-demo-app"}

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: deployment-validation
  namespace: default
  labels:
    app: sre-demo-app
    component: monitoring
spec:
  groups:
  - name: deployment.validation
    interval: 30s
    rules:
    - alert: DeploymentAvailabilityViolation
      expr: |
        (
          sum(rate(http_requests_total{status_code!~"5.."}[5m])) / 
          sum(rate(http_requests_total[5m])) * 100
        ) < 99.5
      for: 2m
      labels:
        severity: critical
        component: deployment
        slo: availability
      annotations:
        summary: "Deployment caused availability SLO violation"
        description: "Availability has dropped to {{ $value }}% (target: 99.5%)"
        
    - alert: DeploymentLatencyViolation
      expr: |
        histogram_quantile(0.95, 
          sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
        ) > 0.8
      for: 5m
      labels:
        severity: warning
        component: deployment
        slo: latency
      annotations:
        summary: "Deployment caused latency SLO violation"
        description: "P95 latency is {{ $value }}s (threshold: 0.8s)"
        
    - alert: DeploymentErrorRateHigh
      expr: |
        (
          sum(rate(http_requests_total{status_code=~"5.."}[5m])) / 
          sum(rate(http_requests_total[5m])) * 100
        ) > 5
      for: 1m
      labels:
        severity: critical
        component: deployment
        slo: error_rate
      annotations:
        summary: "Deployment caused high error rate"
        description: "Error rate is {{ $value }}% (threshold: 5%)"

    - alert: DeploymentBusinessOperationsDown
      expr: |
        (
          sum(rate(business_operations_total{status="success"}[5m])) / 
          sum(rate(business_operations_total[5m])) * 100
        ) < 95
      for: 3m
      labels:
        severity: critical
        component: deployment
        slo: business_operations
      annotations:
        summary: "Deployment affected business operations"
        description: "Business operations success rate: {{ $value }}% (target: 95%)"