---
# Vertical Pod Autoscaler for cost optimization
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sre-demo-vpa
  namespace: default
  labels:
    cost.optimized: "true"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-demo-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: sre-demo-app
      maxAllowed:
        cpu: "1000m"
        memory: "512Mi"
      minAllowed:
        cpu: "50m"
        memory: "64Mi"
      controlledResources: ["cpu", "memory"]

---
# Enhanced HPA with custom metrics
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sre-demo-hpa-optimized
  namespace: default
  labels:
    cost.optimized: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-demo-app
  minReplicas: 1  # Reduced minimum for cost savings
  maxReplicas: 20 # Increased maximum for burst capacity
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics for intelligent scaling
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300  # Longer stabilization for cost savings
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min

---
# Priority Class for cost optimization
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cost-optimized
  labels:
    cost.optimized: "true"
value: 100
globalDefault: false
description: "Priority class for cost-optimized workloads"

---
# Node Affinity for spot instances
apiVersion: v1
kind: ConfigMap
metadata:
  name: cost-optimization-config
  namespace: default
  labels:
    cost.optimized: "true"
data:
  spot-instance-preference: "true"
  cost-optimization-level: "aggressive"
  resource-efficiency-target: "80"
  scaling-policy: |
    # Cost-optimized scaling policy
    scale_up_threshold: 70
    scale_down_threshold: 30
    scale_down_delay: 300
    spot_instance_preference: true
    preemptible_tolerance: high

---
# Pod Disruption Budget for cost-aware deployments
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sre-demo-pdb-cost-optimized
  namespace: default
  labels:
    cost.optimized: "true"
spec:
  selector:
    matchLabels:
      app: sre-demo-app
  maxUnavailable: 50%  # Allow higher disruption for cost savings

---
# Cluster Autoscaler configuration
apiVersion: v1
kind: ConfigMap
metadata:
