apiVersion: v1
kind: Service
metadata:
  name: sre-demo-service
  labels:
    app: sre-demo-app
    component: backend
    deployment.method: gitops
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/load-balancer-type: External
    gitops.argoproj.io/sync-wave: "2"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sre-demo-app
  sessionAffinity: None
  externalTrafficPolicy: Cluster

---
apiVersion: v1
kind: Service
metadata:
  name: sre-demo-headless
  labels:
    app: sre-demo-app
    component: backend
    deployment.method: gitops
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    gitops.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: sre-demo-app